apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kan.fullname" . }}
  labels:
    {{- include "kan.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable | default "0" }}
  selector:
    matchLabels:
      {{- include "kan.selectorLabels" . | nindent 6 }}
