apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kan.fullname" . }}
  labels:
    {{- include "kan.labels" . | nindent 4 }}
type: Opaque
data:
  BETTER_AUTH_SECRET: "{{ include "kan.betterAuthSecret" . }}"
