apiVersion: v1
kind: Service
metadata:
  name: {{ include "kan.fullname" . }}
  labels:
    {{- include "kan.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kan.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kan.selectorLabels" . | nindent 4 }}
